### PR TITLE
Project Wide Improvements

### PR DESCRIPTION
**Pull request by westonganger**
I really liked this translation engine but it was not even in a usable state off the bat. My changes snowballed into a much bigger PR than most would prefer however I think this project needed a lot of work and this helps alleviate a lot of the basics. 

Here is a large suite of improvements to help move things forward.

As stated in Changelog:

```
  * Support Ruby 2.3+, Rails 5.0+
  * Allow editing primary locale (Solves #130)
  * Allow leaving out variables for translated phrases (Solves #133, #57)
  * Add form Success and Error alerts
  * Show Validation Errors on Failure
  * Dont clear fields on error
  * Clarify Action Names
  * Added Cancel Button
  * Floating Save/Cancel Button
  * Convert to Ruby 1.9+ hash syntax
  * Add Github Actions CI Test Suite
  * Simplify Controllers and Routes
  * Cleanup Assets
  * Added screenshots
```

TODO:

- Ensure all tests pass (Currently giving some internal translation missing error, having a bit of a moment debugging it...)
- Complete integration of Github Actions workflow.

### CODE REVIEW

**Comment by thomasdarde** [comment]
Excellent news ! I don't have time to help , but will review this PR as soon as tests pass

**Comment by thomasdarde** [comment]
@westonganger any news on this one ?

**Comment by westonganger** [comment]
I sunk significant time into this PR already but I have no time to look at this again anytime soon. Would love if you or someone could pick up the torch here. This project really could use the improvements.

**Comment by thomasdarde** [comment]
Hi @westonganger

FYI I did review the branch at last !
Excellent work, but I have 2 remaining blockers

1 - I have an error when editing certain locales (english which is secondary in this case)
Screenshot 2021-07-28 at 02 58 13

2 - Tests are not green yet


And also a small one here : Screenshot 2021-07-28 at 02 58 03

**Comment by thomasdarde** [comment]
Hi @westonganger 
I did add your github actions workflow to the latest release.

Fill free if you have time and still want changes to be integrated to send again this PR in smaller parts

**Pull request closed without merging**
