### PR TITLE
Use before_action instead of deprecated before_filter

### PR DESCRIPTION
**Pull request by NomNomCameron**
#125

### CODE REVIEW

**Comment by thomasdarde** [comment]
Thanks @NomNomCameron ! I will check if Travis CI is ok !
Do you use this branch wis a rails 5 project, is it working well ?

**Comment by thomasdarde** [comment]
It seems we need to remove ruby 1.9.3 support (wich is ok for me If you update the PR)

**Comment by NomNomCameron** [comment]
I am in the process of updating our app to rails 5, so far the only problems I've run into were tolk using before_filter, and for some reason I can only get version 1.5.1 from rubygems... which pulled in an error from `application.css` but that problem isn't on this repo.

**Comment by NomNomCameron** [comment]
this should be good to merge now @thomasdarde

**Comment by thomasdarde** [comment]
Thanks @NomNomCameron I will try to make a release next week

**Comment by NomNomCameron** [comment]
Sounds good Thomas. Thanks for getting this merged.

**Pull request merged**
