### PR TITLE
Support for https://github.com/fnando/i18n-js

### PR DESCRIPTION
**Pull request by bogdanvlviv**

### CODE REVIEW

**Comment by thomasdarde** [comment]
Hello @bogdanvlviv , Thank you for your PR. Could you explain the idea  ?
And also check for the tests ?

**Comment by bogdanvlviv** [comment]
The idea is managing all i18n translations in tolk also if we using (i18n-js)[https://github.com/fnando/i18n-js] strategy for translations for js. Your thoughts?
test failed because of incorrect  travis config. rvm can't install ruby 2.4, the version only in preview2

**Comment by thomasdarde** [comment]
Thanks for the tests 👍 , i18n-js seems interesting indeed.
But I don't understand where it fits in tolk ? (it normally translates static yml files wich are imported in the db) these files can be the source for i18n-js i believe

**Comment by bogdanvlviv** [comment]
```ruby
  Tolk::Locale.dump_all # generate yml files 
  I18n.reload! # reload translations.
  # We don't need restarting server.
  # Translations will be availeble at once. It is cool :)
  I18n::JS.export if defined? I18n::JS # export translations for javascript.
  # We can to config which translations must go in javascript, thanks i18n-js
  # after all translations will be available without restarting servers and running a rake tasks
  redirect_to request.referrer
end
```

**Pull request merged**
