### PR TITLE
Added escaping quotes to tolk_phrases.key in order to work with SQL Server/TinyTds.

### PR DESCRIPTION
**Pull request by eklamer1**
SQL Server has a problem with key as a field name. These changes are working with SQL Server and TinyTds in my development environment.

I tested MySQL, and it works but must be set to ANSI mode. I was unable to test on PostGreSQL or SQLite due to difficulties setting them up in my Windows environment.

### CODE REVIEW

**Comment by thomasdarde** [comment]
I can't merge easily this PR, could you sqash your 2 commits and make a new one ? 

Thanks

**Comment by eklamer1** [comment]
Sorry, this was my first time doing anything on GitHub. The first one has
.idea and other folders that I didn't know to exclude. I'll see if I can
figure it out.

**Comment by thomasdarde** [comment]
Good luck !

In general "git rebase -i" is your savior in these cases. 




-

 <https://sigilium.com/signatures/rcDC_ix8fTp6sz8EERs4GCcz41fX0rc/link>

**Comment by thomasdarde** [comment]
Don't hesitate to reopen it if you want

**Pull request closed without merging**
